export const clientssMock = [
    {
      subject_id: 1,
      birth_year: 2006,
      gender: 'S1-Female',
      race_factor: 'R1 - Black',
      ethnic_factor: 'E0 - Non - Hispanic',
      hasAlmondAllergy: false,
      hasBrazilAllergy: false,
      hasMilkAllergy: false,
      hasPecanAllergy: false,
      hasFishAllergy: false,
      hasPeanutAllergy: false,
      hasPistachioAllergy: false,
      hasHazelAllergy: false,
      hasCashewAllergy: false,
      hasWheatAllergy: false,
      hasWalnutAllergy: false,
      hasSoyAllergy: false,
      hasSeaFoodAllergy: false,
      hasSesameAllergy: false,
      hasEggAllergy: false,
      hasTreenutAllergy: false,
    },
  {
    subject_id: 2,
    birth_year: 2006,
    gender: 'S1-male',
    race_factor: 'R1 - White',
    ethnic_factor: 'E0 - Non - Hispanic',
    hasAlmondAllergy: true,
    hasBrazilAllergy: false,
    hasMilkAllergy: true,
    hasPecanAllergy: true,
    hasFishAllergy: false,
    hasPeanutAllergy: false,
    hasPistachioAllergy: false,
    hasHazelAllergy: false,
    hasCashewAllergy: true,
    hasWheatAllergy: false,
    hasWalnutAllergy: true,
    hasSoyAllergy: false,
    hasSeaFoodAllergy: false,
    hasSesameAllergy: false,
    hasEggAllergy: false,
    hasTreenutAllergy: false,
  },
  {
    subject_id: 3,
    birth_year: 2006,
    gender: 'S1-male',
    race_factor: 'R1 - White',
    ethnic_factor: 'E0 - Non - Hispanic',
    hasAlmondAllergy: true,
    hasBrazilAllergy: false,
    hasMilkAllergy: true,
    hasPecanAllergy: true,
    hasFishAllergy: false,
    hasPeanutAllergy: false,
    hasPistachioAllergy: false,
    hasHazelAllergy: false,
    hasCashewAllergy: false,
    hasWheatAllergy: false,
    hasWalnutAllergy: true,
    hasSoyAllergy: false,
    hasSeaFoodAllergy: false,
    hasSesameAllergy: false,
    hasEggAllergy: false,
    hasTreenutAllergy: false,
  },
    {
      subject_id: 4,
      birth_year: 2006,
      gender: 'S1-male',
      race_factor: 'R1 - White',
      ethnic_factor: 'E0 - Non - Hispanic',
      hasAlmondAllergy: true,
      hasBrazilAllergy: false,
      hasMilkAllergy: true,
      hasPecanAllergy: true,
      hasFishAllergy: false,
      hasPeanutAllergy: false,
      hasPistachioAllergy: false,
      hasHazelAllergy: false,
      hasCashewAllergy: false,
      hasWheatAllergy: false,
      hasWalnutAllergy: true,
      hasSoyAllergy: false,
      hasSeaFoodAllergy: false,
      hasSesameAllergy: false,
      hasEggAllergy: false,
      hasTreenutAllergy: false,
    },
    {
      subject_id: 4,
      birth_year: 2006,
      gender: 'S1-male',
      race_factor: 'R1 - White',
      ethnic_factor: 'E0 - Non - Hispanic',
      hasAlmondAllergy: true,
      hasBrazilAllergy: false,
      hasMilkAllergy: true,
      hasPecanAllergy: true,
      hasFishAllergy: false,
      hasPeanutAllergy: false,
      hasPistachioAllergy: false,
      hasHazelAllergy: false,
      hasCashewAllergy: false,
      hasWheatAllergy: false,
      hasWalnutAllergy: true,
      hasSoyAllergy: false,
      hasSeaFoodAllergy: false,
      hasSesameAllergy: false,
      hasEggAllergy: false,
      hasTreenutAllergy: false,
    },
    {
      subject_id: 5,
      birth_year: 2006,
      gender: 'S1-male',
      race_factor: 'R1 - White',
      ethnic_factor: 'E0 - Non - Hispanic',
      hasAlmondAllergy: true,
      hasBrazilAllergy: false,
      hasMilkAllergy: true,
      hasPecanAllergy: true,
      hasFishAllergy: false,
      hasPeanutAllergy: false,
      hasPistachioAllergy: false,
      hasHazelAllergy: false,
      hasCashewAllergy: false,
      hasWheatAllergy: false,
      hasWalnutAllergy: true,
      hasSoyAllergy: false,
      hasSeaFoodAllergy: false,
      hasSesameAllergy: false,
      hasEggAllergy: false,
      hasTreenutAllergy: false,
    },
    {
      subject_id: 6,
      birth_year: 2006,
      gender: 'S1-male',
      race_factor: 'R1 - White',
      ethnic_factor: 'E0 - Non - Hispanic',
      hasAlmondAllergy: true,
      hasBrazilAllergy: false,
      hasMilkAllergy: true,
      hasPecanAllergy: true,
      hasFishAllergy: false,
      hasPeanutAllergy: false,
      hasPistachioAllergy: false,
      hasHazelAllergy: false,
      hasCashewAllergy: false,
      hasWheatAllergy: false,
      hasWalnutAllergy: true,
      hasSoyAllergy: false,
      hasSeaFoodAllergy: false,
      hasSesameAllergy: false,
      hasEggAllergy: false,
      hasTreenutAllergy: false,
    },
    {
      subject_id: 7,
      birth_year: 2006,
      gender: 'S1-male',
      race_factor: 'R1 - White',
      ethnic_factor: 'E0 - Non - Hispanic',
      hasAlmondAllergy: true,
      hasBrazilAllergy: false,
      hasMilkAllergy: true,
      hasPecanAllergy: true,
      hasFishAllergy: false,
      hasPeanutAllergy: false,
      hasPistachioAllergy: false,
      hasHazelAllergy: false,
      hasCashewAllergy: false,
      hasWheatAllergy: false,
      hasWalnutAllergy: true,
      hasSoyAllergy: false,
      hasSeaFoodAllergy: false,
      hasSesameAllergy: false,
      hasEggAllergy: false,
      hasTreenutAllergy: false,
    },
    {
      subject_id: 8,
      birth_year: 2006,
      gender: 'S1-male',
      race_factor: 'R1 - White',
      ethnic_factor: 'E0 - Non - Hispanic',
      hasAlmondAllergy: true,
      hasBrazilAllergy: false,
      hasMilkAllergy: true,
      hasPecanAllergy: true,
      hasFishAllergy: false,
      hasPeanutAllergy: false,
      hasPistachioAllergy: false,
      hasHazelAllergy: false,
      hasCashewAllergy: false,
      hasWheatAllergy: false,
      hasWalnutAllergy: true,
      hasSoyAllergy: false,
      hasSeaFoodAllergy: false,
      hasSesameAllergy: false,
      hasEggAllergy: false,
      hasTreenutAllergy: false,
    },








  ]
;
